import { describe, expect, test } from 'bun:test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ReactElement } from 'react';
import { Navigate } from 'react-router-dom';

// SCSS modules are not compiled outside Vite; give them class-name proxies so the
// full page tree can load in tests (Bun returns an empty object otherwise).
Bun.plugin({
  name: 'scss-css-modules',
  setup(build) {
    build.onLoad({ filter: /\.s?css$/ }, () => ({
      contents:
        "export default new Proxy({}, { get: (_target, key) => (typeof key === 'string' ? key : undefined) });",
      loader: 'js',
    }));
  },
});

type RouteEntry = { path: string; element: ReactElement };

const componentName = (element: ReactElement | undefined) =>
  typeof element?.type === 'function'
    ? (element.type as { name?: string }).name ?? ''
    : String(element?.type);

describe('quota windows page loads by default', () => {
  test('root and unknown routes redirect to /windows while dashboard stays reachable', async () => {
    await import('../src/i18n/index');
    const { createMainRoutes } = await import('../src/router/routeConfig');
    const routes = createMainRoutes(false) as unknown as RouteEntry[];
    const elementFor = (path: string) => routes.find((route) => route.path === path)?.element;

    const root = elementFor('/');
    expect(root?.type).toBe(Navigate);
    expect((root?.props as { to: string }).to).toBe('/windows');

    const fallback = elementFor('*');
    expect(fallback?.type).toBe(Navigate);
    expect((fallback?.props as { to: string }).to).toBe('/windows');

    expect(componentName(elementFor('/quota'))).toBe('QuotaPage');
    expect(componentName(elementFor('/windows'))).toBe('QuotaWindowsPage');
    expect(componentName(elementFor('/dashboard'))).toBe('DashboardPage');

    const pluginRoutes = createMainRoutes(true) as unknown as RouteEntry[];
    expect(componentName(pluginRoutes.find((route) => route.path === '/dashboard')?.element)).toBe(
      'DashboardPage',
    );

    const proofPath = resolve(
      import.meta.dir,
      '../artifacts/cpamc/quota-default-window-20260922/proof/route-resolution.html',
    );
    mkdirSync(dirname(proofPath), { recursive: true });
    writeFileSync(
      proofPath,
      `<!doctype html><html><head><meta charset="utf-8"><title>CPAMC default route proof</title></head>` +
        `<body><h1>Default landing route: /windows (QuotaWindowsPage)</h1>` +
        `<table><tr><th>path</th><th>resolves to</th></tr>` +
        routes
          .map((route) => `<tr><td>${route.path}</td><td>${componentName(route.element)}</td></tr>`)
          .join('') +
        `</table><p>Root redirect target: ${(root?.props as { to: string }).to}</p>` +
        `<p>Generated by tests/defaultRoute.test.ts from the live route table.</p></body></html>`,
    );
  });
});
